openapi: 3.0.3
info:
  title: LinkFlow Credential Service API
  description: Secure credential management service
  version: 1.0.0

servers:
  - url: http://localhost:8006
    description: Local development

tags:
  - name: Credentials
    description: Credential management
  - name: Types
    description: Credential types

paths:
  /api/v1/credentials:
    get:
      tags: [Credentials]
      summary: List credentials
      operationId: listCredentials
      security:
        - bearerAuth: []
      parameters:
        - name: type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of credentials
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Credential'
    post:
      tags: [Credentials]
      summary: Create credential
      operationId: createCredential
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCredentialRequest'
      responses:
        '201':
          description: Credential created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credential'

  /api/v1/credentials/{id}:
    get:
      tags: [Credentials]
      summary: Get credential
      operationId: getCredential
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Credential details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credential'
    put:
      tags: [Credentials]
      summary: Update credential
      operationId: updateCredential
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCredentialRequest'
      responses:
        '200':
          description: Credential updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credential'
    delete:
      tags: [Credentials]
      summary: Delete credential
      operationId: deleteCredential
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Credential deleted

  /api/v1/credentials/{id}/test:
    post:
      tags: [Credentials]
      summary: Test credential
      operationId: testCredential
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Credential test result
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /api/v1/credentials/types:
    get:
      tags: [Types]
      summary: List credential types
      operationId: listCredentialTypes
      responses:
        '200':
          description: List of credential types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CredentialType'

  /api/v1/credentials/oauth/{provider}/authorize:
    get:
      tags: [Credentials]
      summary: Start OAuth flow
      operationId: oauthAuthorize
      security:
        - bearerAuth: []
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
        - name: credentialId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        '302':
          description: Redirect to OAuth provider

  /api/v1/credentials/oauth/{provider}/callback:
    get:
      tags: [Credentials]
      summary: OAuth callback
      operationId: oauthCallback
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OAuth completed

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Credential:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
        description:
          type: string
        isShared:
          type: boolean
        isActive:
          type: boolean
        lastUsedAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time

    CreateCredentialRequest:
      type: object
      required: [name, type, data]
      properties:
        name:
          type: string
        type:
          type: string
        data:
          type: object
        description:
          type: string
        isShared:
          type: boolean
          default: false

    UpdateCredentialRequest:
      type: object
      properties:
        name:
          type: string
        data:
          type: object
        description:
          type: string
        isShared:
          type: boolean

    CredentialType:
      type: object
      properties:
        type:
          type: string
        name:
          type: string
        description:
          type: string
        icon:
          type: string
        authFlow:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/CredentialField'

    CredentialField:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        label:
          type: string
        required:
          type: boolean
        sensitive:
          type: boolean
        placeholder:
          type: string
        help:
          type: string
        default:
          type: string
        options:
          type: array
          items:
            type: string
