openapi: 3.0.3
info:
  title: LinkFlow User Service API
  description: User management, teams, and roles API
  version: 1.0.0

servers:
  - url: http://localhost:8082
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        avatar:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time

    Team:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        ownerId:
          type: string
        createdAt:
          type: string
          format: date-time

    Role:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        permissions:
          type: array
          items:
            type: string

paths:
  /health:
    get:
      tags: [Health]
      summary: Health check
      responses:
        '200':
          description: Healthy

  /api/v1/users:
    get:
      tags: [Users]
      summary: List users
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: status
          schema:
            type: string
        - in: query
          name: roleId
          schema:
            type: string
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer

  /api/v1/users/{id}:
    get:
      tags: [Users]
      summary: Get user by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details
        '404':
          description: User not found

    put:
      tags: [Users]
      summary: Update user
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                avatar:
                  type: string
                status:
                  type: string
      responses:
        '200':
          description: User updated
        '404':
          description: User not found

    delete:
      tags: [Users]
      summary: Delete user
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted

  /api/v1/users/{id}/permissions:
    get:
      tags: [Users]
      summary: Get user permissions
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User permissions

  /api/v1/users/teams:
    get:
      tags: [Teams]
      summary: List teams
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of teams

    post:
      tags: [Teams]
      summary: Create team
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Team created

  /api/v1/users/teams/{id}:
    get:
      tags: [Teams]
      summary: Get team
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Team details

    put:
      tags: [Teams]
      summary: Update team
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Team updated

    delete:
      tags: [Teams]
      summary: Delete team
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Team deleted

  /api/v1/users/teams/{id}/members:
    post:
      tags: [Teams]
      summary: Add team member
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId]
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: Member added

  /api/v1/users/teams/{id}/members/{userId}:
    delete:
      tags: [Teams]
      summary: Remove team member
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Member removed

  /api/v1/users/roles:
    get:
      tags: [Roles]
      summary: List roles
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of roles

  /api/v1/users/roles/{id}/assign:
    post:
      tags: [Roles]
      summary: Assign role to user
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Role ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId]
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: Role assigned

  /api/v1/users/roles/{id}/revoke:
    delete:
      tags: [Roles]
      summary: Revoke role from user
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId]
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: Role revoked

  /api/v1/users/permissions:
    get:
      tags: [Permissions]
      summary: List available permissions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of permissions
