openapi: 3.0.3
info:
  title: LinkFlow Webhook Service API
  description: Webhook management and processing service
  version: 1.0.0

servers:
  - url: http://localhost:8007
    description: Local development

tags:
  - name: Webhooks
    description: Webhook management
  - name: Incoming
    description: Incoming webhook endpoints

paths:
  /api/v1/webhooks:
    get:
      tags: [Webhooks]
      summary: List webhooks
      operationId: listWebhooks
      security:
        - bearerAuth: []
      parameters:
        - name: workflowId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of webhooks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Webhook'
    post:
      tags: [Webhooks]
      summary: Create webhook
      operationId: createWebhook
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWebhookRequest'
      responses:
        '201':
          description: Webhook created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'

  /api/v1/webhooks/{id}:
    get:
      tags: [Webhooks]
      summary: Get webhook
      operationId: getWebhook
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Webhook details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
    delete:
      tags: [Webhooks]
      summary: Delete webhook
      operationId: deleteWebhook
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Webhook deleted

  /webhook/{path}:
    post:
      tags: [Incoming]
      summary: Receive webhook
      operationId: receiveWebhook
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
        - name: X-Webhook-Signature
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
          application/x-www-form-urlencoded:
            schema:
              type: object
      responses:
        '200':
          description: Webhook processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookResponse'
        '404':
          description: Webhook not found
        '401':
          description: Invalid signature

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Webhook:
      type: object
      properties:
        id:
          type: string
          format: uuid
        workflowId:
          type: string
          format: uuid
        nodeId:
          type: string
        path:
          type: string
        method:
          type: string
          enum: [GET, POST, PUT, DELETE, PATCH]
        secret:
          type: string
        isActive:
          type: boolean
        requireAuth:
          type: boolean
        rateLimit:
          type: integer
        lastCalledAt:
          type: string
          format: date-time
        callCount:
          type: integer
        url:
          type: string
        createdAt:
          type: string
          format: date-time

    CreateWebhookRequest:
      type: object
      required: [workflowId, nodeId]
      properties:
        workflowId:
          type: string
          format: uuid
        nodeId:
          type: string
        path:
          type: string
        method:
          type: string
          enum: [GET, POST, PUT, DELETE, PATCH]
          default: POST
        requireAuth:
          type: boolean
          default: false
        rateLimit:
          type: integer
          default: 100

    WebhookResponse:
      type: object
      properties:
        success:
          type: boolean
        executionId:
          type: string
          format: uuid
        message:
          type: string
