openapi: 3.0.3
info:
  title: LinkFlow Workflow Service API
  description: Workflow management service for LinkFlow
  version: 1.0.0

servers:
  - url: http://localhost:8003
    description: Local development
  - url: https://api.linkflow.io
    description: Production

tags:
  - name: Workflows
    description: Workflow CRUD operations
  - name: Versions
    description: Workflow versioning
  - name: Templates
    description: Workflow templates

paths:
  /api/v1/workflows:
    get:
      tags: [Workflows]
      summary: List workflows
      operationId: listWorkflows
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: status
          in: query
          schema:
            type: string
            enum: [active, inactive, all]
        - name: search
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of workflows
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowListResponse'
    post:
      tags: [Workflows]
      summary: Create a new workflow
      operationId: createWorkflow
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkflowRequest'
      responses:
        '201':
          description: Workflow created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'


  /api/v1/workflows/{id}:
    get:
      tags: [Workflows]
      summary: Get workflow by ID
      operationId: getWorkflow
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Workflow details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags: [Workflows]
      summary: Update workflow
      operationId: updateWorkflow
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkflowRequest'
      responses:
        '200':
          description: Workflow updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
    delete:
      tags: [Workflows]
      summary: Delete workflow
      operationId: deleteWorkflow
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Workflow deleted

  /api/v1/workflows/{id}/activate:
    post:
      tags: [Workflows]
      summary: Activate workflow
      operationId: activateWorkflow
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Workflow activated

  /api/v1/workflows/{id}/deactivate:
    post:
      tags: [Workflows]
      summary: Deactivate workflow
      operationId: deactivateWorkflow
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Workflow deactivated

  /api/v1/workflows/{id}/execute:
    post:
      tags: [Workflows]
      summary: Execute workflow manually
      operationId: executeWorkflow
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
      responses:
        '202':
          description: Execution started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Workflow:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        userId:
          type: string
          format: uuid
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        connections:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
        settings:
          $ref: '#/components/schemas/WorkflowSettings'
        status:
          type: string
          enum: [active, inactive, error]
        isActive:
          type: boolean
        version:
          type: integer
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Node:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        position:
          type: object
          properties:
            x:
              type: number
            y:
              type: number
        parameters:
          type: object
        disabled:
          type: boolean

    Connection:
      type: object
      properties:
        id:
          type: string
        source:
          type: string
        target:
          type: string
        sourcePort:
          type: string
        targetPort:
          type: string

    WorkflowSettings:
      type: object
      properties:
        timeout:
          type: integer
        retryOnFailure:
          type: boolean
        maxRetries:
          type: integer
        timezone:
          type: string

    CreateWorkflowRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
        description:
          type: string
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        connections:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
        tags:
          type: array
          items:
            type: string

    UpdateWorkflowRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        connections:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
        tags:
          type: array
          items:
            type: string

    WorkflowListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Workflow'
        pagination:
          $ref: '#/components/schemas/Pagination'

    ExecutionResponse:
      type: object
      properties:
        executionId:
          type: string
          format: uuid
        status:
          type: string
        startedAt:
          type: string
          format: date-time

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
